/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Maze.view;

import Maze.controller.InputHandler;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class MainWindow extends javax.swing.JFrame {

    GameWindow game = new GameWindow();
    InputHandler input = new InputHandler(this.game);
    private int hp;
    private int armor;
    private boolean isRunning=true;
    
    private static MainWindow instance = new MainWindow();
    
    public static MainWindow getInstance(){
      return instance;
   }
    
    private MainWindow() {
        
        this.setVisible(true);
        
        setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
        add(game);
        pack();
        game.setBounds(10,160, 700, 500);
        game.setVisible(true);
        game.start();
        setResizable(false);
        setLocationRelativeTo(null);
        game.requestFocus();
        initComponents();
        jPanel1.setVisible(false);
        jProgressBar1.setValue(100);
        jProgressBar2.setValue(100);
    }
    
    
    
    public void pause()
    {
        game.stop();
        game.setVisible(false);
        jPanel1.setVisible(true);
        System.out.println("pause");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maze Runner");
        setPreferredSize(new java.awt.Dimension(730, 700));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Minecraft", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 50, 44, 37);

        jProgressBar1.setValue(90);
        jProgressBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(160, 50, 152, 30);

        jProgressBar2.setValue(80);
        jProgressBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(450, 50, 152, 30);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Minecraft", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Resume");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(308, 203, 84, 25);

        jLabel12.setFont(new java.awt.Font("Minecraft", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("How to Play");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(282, 243, 135, 25);

        jLabel13.setFont(new java.awt.Font("Minecraft", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Back to Main Menu");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(245, 283, 209, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 160, 700, 500);

        jLabel4.setFont(new java.awt.Font("Minecraft", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bullets");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 100, 124, 37);

        jLabel3.setFont(new java.awt.Font("Minecraft", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Armor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 50, 110, 37);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bullets.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 102, 32, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bullets.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(365, 102, 32, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bullets.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 102, 32, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bullets.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(395, 102, 32, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bullets.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 102, 32, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bullets.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(425, 102, 32, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UIBACK.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        game.start();
        game.setVisible(true);
        jPanel1.setVisible(false);
        game.requestFocus();
    }//GEN-LAST:event_jLabel11MousePressed

   
    private void HideAll()
    {
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jProgressBar1.setVisible(false);
        jProgressBar2.setVisible(false);
        
    }
    

    public void setBullets(int bullets)
    {
        switch(bullets){
            case 0:
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                break;
            case 1:
                jLabel5.setVisible(true);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
            case 2:
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                break;
            case 3:
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel8.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                break;
            case 4:
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel8.setVisible(true);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                break;
            case 5:
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel8.setVisible(true);
                jLabel9.setVisible(true);
                jLabel10.setVisible(false);
                break;
            case 6:
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel8.setVisible(true);
                jLabel9.setVisible(true);
                jLabel10.setVisible(true);
                break;                
        }
    }
        
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables
}
