/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Maze.view;

import Maze.controller.GameLost;
import Maze.controller.InputHandler;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import static java.lang.Math.abs;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class MainWindow extends javax.swing.JFrame {

    GameWindow game = GameWindow.getInstance();
    InputHandler input = new InputHandler(this.game);
    private int hp=100;
    private int armor=0;
    private boolean isRunning=true;
    private Timer _timer;
    private DateFormat _fmt = DateFormat.getTimeInstance(DateFormat.LONG);
    private Calendar _calendar = Calendar.getInstance();
    private TimerLabel timer = new TimerLabel();
    private static MainWindow instance = new MainWindow();
    
    
    public static MainWindow getInstance(){
      return instance;
   }
    
    private MainWindow() {
        
        this.setVisible(true);
        this.add(timer);
        setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
      /*add(game);
        pack();
        game.setBounds(10,160, 700, 500);
        game.setVisible(true);
        game.start();
        game.requestFocus();
        */
        setResizable(false);
        setLocationRelativeTo(null);        
        initComponents();
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
        jProgressBar1.setValue(100);
        jProgressBar2.setValue(0);
    }
    
    
    public void inflictDamage(int damage)
    {
        armor = jProgressBar2.getValue();
        hp = jProgressBar1.getValue();
        if(armor>0)
        {
            armor-=damage;
            damage=0;
            if(armor<0)
            {
                damage=abs(armor);
                armor=0;
            }
            jProgressBar2.setValue(armor);
            if(damage>0)
            {
                hp-=damage;
                if(hp<0)
                {
                    GameLost lost = new GameLost();
                    lost.execute();
                }
                jProgressBar1.setValue(hp);
            }
        }
        else
        {
            hp-=damage;
            if(hp<0)
            {
                GameLost lost = new GameLost();
                lost.execute();
            }
            else
                jProgressBar1.setValue(hp);
        }        
        
    }
   
    
    public void Heal(int heal)
    {
        hp +=heal;
        if(hp>100)
            hp=100;
        jProgressBar1.setValue(hp);
    }
    
    public void AddArmor(int arm)
    {
        armor +=arm;
        if(armor>100)
            armor=100;
        jProgressBar2.setValue(armor);
    }
    
    
    public void pause()
    {
        game.stop();
        game.setVisible(false);
        jPanel1.setVisible(true);
        System.out.println("pause");
    }
    
    public void winner()
    {
        game.stop();
        game.setVisible(false);
        jPanel2.setVisible(true);
    }
    
    public void lost()
    {
        game.stop();
        game.setVisible(false);
        jPanel3.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maze Runner");
        setPreferredSize(new java.awt.Dimension(730, 700));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Minecraft", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 50, 44, 37);

        jProgressBar1.setValue(90);
        jProgressBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(160, 50, 152, 30);

        jProgressBar2.setValue(80);
        jProgressBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(450, 50, 152, 30);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Minecraft", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DIED.png"))); // NOI18N
        jPanel3.add(jLabel16);
        jLabel16.setBounds(70, 40, 560, 290);

        jLabel17.setFont(new java.awt.Font("Minecraft", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Click here to quit");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
        });
        jPanel3.add(jLabel17);
        jLabel17.setBounds(220, 350, 240, 90);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 160, 700, 500);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Minecraft", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("WINNER WINNER CHICKEN DINNER");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(70, 160, 560, 170);

        jLabel15.setFont(new java.awt.Font("Minecraft", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Click here to quit");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel2.add(jLabel15);
        jLabel15.setBounds(220, 350, 240, 90);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 160, 700, 500);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Minecraft", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Resume");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(308, 203, 84, 25);

        jLabel12.setFont(new java.awt.Font("Minecraft", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("How to Play");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(282, 243, 135, 25);

        jLabel13.setFont(new java.awt.Font("Minecraft", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Quit");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(325, 283, 50, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 160, 700, 500);

        jLabel4.setFont(new java.awt.Font("Minecraft", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Time");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 100, 400, 37);

        jLabel3.setFont(new java.awt.Font("Minecraft", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Armor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 50, 110, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UIBACK.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        unpause();
    }//GEN-LAST:event_jLabel11MousePressed

    public void unpause()
    {
        game.start();
        game.setVisible(true);
        jPanel1.setVisible(false);
        game.requestFocus();
    }
    
    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel17MousePressed

   
    private void HideAll()
    {
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jProgressBar1.setVisible(false);
        jProgressBar2.setVisible(false);
        
    }
    

    
        
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables
}
